server:
  port: 8888

management.endpoints.web:
  include: '*'
  
spring:
  application:
    name: agro-configserver-ms
  cloud:
    config:
      server:
        git:
          defaultLabel: master
          uri: https://github.com/jimmyej/agro-fileserver
  security:
    user:
      name: root
      password: s3cr3t